name: Reuseable Workflow Caller

on:
  workflow_dispatch:

jobs:
  call-reuseable-workflow-path:
    name: Invoke reuseable workflow with relative path
    uses: ./.github/workflows/06-authoring-actions--02-reuseable-workflows-source.yaml
    with:
      foo: bar
      environment: staging
    secrets: inherit

  call-reuseable-workflow-sha:
    name: Invoke reuseable workflow with repo + commit hash
    uses: RohitZe/gactions/.github/workflows/06-authoring-actions--02-reuseable-workflows-source.yaml@c00db42946e9556458fa3ee974bf193084fcf3c7
    with:
      foo: bar
      environment: production
    secrets:
      EXAMPLE_REPOSITORY_SECRET: ${{ secrets.EXAMPLE_REPOSITORY_SECRET }}
